label: IMMUTABLE

catalog: MS-003
speed: "33⅓"
genre: HARDGROOVE

serial: MS-4018
idx: A5-T12

code: 93428-X
sector: 09C

coords:
  lat: 48°12'45"N
  lon: 16°22'30"E

colors:
  bg: "#8C00FF"   # ultraviolet purple
  ink: "#00FFD1"  # electric cyan
